[tool.poetry]
name = "stripe-microservice"
version = "0.1.0"
description = ""
authors = ["modgeosys <kweller@moderngeosystems.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
