AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  stripe-ms

  SAM Template for stripe-ms

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
Resources:
  CreatePaymentIntentFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: create_payment_intent/
      Handler: app.lambda_handler
      Runtime: python3.10
      Architectures:
      - x86_64
      Events:
        CreatePaymentIntentApi:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /payment_intent
            Method: post
  ConfirmPaymentIntentFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: capture_payment_intent/
      Handler: app.lambda_handler
      Runtime: python3.10
      Architectures:
      - x86_64
      Events:
        ConfirmPaymentIntentApi:
          Type: Api
          Properties:
            Path: /payment_intent
            Method: put
  CancelPaymentIntentFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: cancel_payment_intent/
      Handler: app.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64
      Events:
        CancelPaymentIntentApi:
          Type: Api
          Properties:
            Path: /payment_intent
            Method: delete

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CreatePaymentIntentApi:
    Description: API Gateway endpoint URL for Prod stage for Create Payment Intent function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/create/"
  CreatePaymentIntentFunction:
    Description: Create Payment Intent Lambda Function ARN
    Value: !GetAtt CreatePaymentIntentFunction.Arn
  CreatePaymentIntentFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt CreatePaymentIntentFunctionRole.Arn
  ConfirmPaymentIntentApi:
    Description: API Gateway endpoint URL for Prod stage for Confirm Payment Intent function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/confirm/"
  ConfirmPaymentIntentFunction:
    Description: Confirm Payment Intent Lambda Function ARN
    Value: !GetAtt ConfirmPaymentIntentFunction.Arn
  ConfirmPaymentIntentFunctionIamRole:
    Description: Implicit IAM Role created for Confirm Payment Intent function
    Value: !GetAtt ConfirmPaymentIntentFunctionRole.Arn
  CancelPaymentIntentApi:
    Description: API Gateway endpoint URL for Prod stage for Cancel Payment Intent function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/cancel/"
  CancelPaymentIntentFunction:
    Description: Cancel Payment Intent Lambda Function ARN
    Value: !GetAtt CancelPaymentIntentFunction.Arn
  CancelPaymentIntentFunctionIamRole:
    Description: Implicit IAM Role created for Cancel Payment Intent function
    Value: !GetAtt CancelPaymentIntentFunctionRole.Arn
